In [1]:
import numpy as np

# List of protein sequences
sequences = [
    "AARCIDGAFRPKATDG",
    "ACDPHSGHFV",
    "ADDVKLWRQRGMSTW",
    "ADKPDESTL",
    "AEENDEENVEEVEENVEENV",
    "AEHQAIIRDVLTASD"
]

# Create a dictionary to map each amino acid to an index
amino_acids = 'ACDEFGHIKLMNPQRSTVWY'
aa_to_index = {aa: i for i, aa in enumerate(amino_acids)}

# Function to convert a sequence to a one-hot encoding
def sequence_to_one_hot(sequence):
    one_hot_encoding = np.zeros((len(sequence), len(amino_acids)))
    for i, aa in enumerate(sequence):
        if aa in aa_to_index:
            one_hot_encoding[i, aa_to_index[aa]] = 1
    return one_hot_encoding

# Create one-hot encodings for all sequences
one_hot_encodings = [sequence_to_one_hot(seq) for seq in sequences]

# Print one-hot encodings for each sequence
for i, seq in enumerate(sequences):
    print(f"Sequence {i + 1}:")
    print(one_hot_encodings[i])
    print()


Sequence 1:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.

In [5]:
from sklearn.preprocessing import LabelBinarizer

# List of protein sequences
sequences = [
    "AARCIDGAFRPKATDG",
    "ACDPHSGHFV",
    "ADDVKLWRQRGMSTW",
    "ADKPDESTL",
    "AEENDEENVEEVEENVEENV",
    "AEHQAIIRDVLTASD"
]

# Join all sequences into a single string
all_amino_acids = ''.join(sequences)

# Get unique amino acids
unique_amino_acids = sorted(set(all_amino_acids))

# Create one-hot encoder
one_hot_encoder = LabelBinarizer()

# Fit and transform on unique amino acids
one_hot_encoder.fit(unique_amino_acids)

# Convert each sequence to one-hot encoding
one_hot_encodings = [one_hot_encoder.transform(seq) for seq in sequences]

# Print one-hot encodings for each sequence
for i, seq in enumerate(sequences):
    print(f"Sequence {i + 1}:")
    print(one_hot_encodings[i])
    print()


ValueError: Expected array-like (array or non-string sequence), got 'AARCIDGAFRPKATDG'

In [6]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# List of protein sequences
sequences = [
    "AARCIDGAFRPKATDG",
    "ACDPHSGHFV",
    "ADDVKLWRQRGMSTW",
    "ADKPDESTL",
    "AEENDEENVEEVEENVEENV",
    "AEHQAIIRDVLTASD"
]

# Join all sequences into a single string
all_amino_acids = ''.join(sequences)

# Get unique amino acids
unique_amino_acids = sorted(set(all_amino_acids))

# Reshape sequences into a 2D array with one row per sequence
reshaped_sequences = [[aa] for aa in all_amino_acids]

# Create one-hot encoder
one_hot_encoder = OneHotEncoder(categories=[unique_amino_acids], sparse=False)

# Fit and transform on reshaped sequences
one_hot_encodings = one_hot_encoder.fit_transform(reshaped_sequences)

# Print one-hot encodings for each sequence
for i, seq in enumerate(sequences):
    print(f"Sequence {i + 1}:")
    print(one_hot_encodings[i])
    print()


Sequence 1:
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Sequence 2:
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Sequence 3:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]

Sequence 4:
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Sequence 5:
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Sequence 6:
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]



/home/sage/.local/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [7]:
import numpy as np

# List of protein sequences
sequences = [
    "AARCIDGAFRPKATDG",
    "ACDPHSGHFV",
    "ADDVKLWRQRGMSTW",
    "ADKPDESTL",
    "AEENDEENVEEVEENVEENV",
    "AEHQAIIRDVLTASD"
]

# Define the set of unique characters (amino acids)
unique_characters = sorted(set(''.join(sequences)))

# Create a mapping from characters to indices
char_to_index = {char: i for i, char in enumerate(unique_characters)}

# Function to convert a sequence to a one-hot encoding
def sequence_to_one_hot(sequence, char_to_index):
    one_hot_encoding = np.zeros((len(sequence), len(char_to_index)))
    for i, char in enumerate(sequence):
        if char in char_to_index:
            one_hot_encoding[i, char_to_index[char]] = 1
    return one_hot_encoding

# Convert each sequence to one-hot encoding
one_hot_encodings = [sequence_to_one_hot(seq, char_to_index) for seq in sequences]

# Print one-hot encodings for each sequence
for i, seq in enumerate(sequences):
    print(f"Sequence {i + 1}:")
    print(one_hot_encodings[i])
    print()


Sequence 1:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Sequence 2:
[[1. 0. 0. 0. 

In [9]:
import torch
from torch.nn.utils.rnn import pad_sequence

# List of protein sequences
sequences = [
    "AARCIDGAFRPKATDG",
    "ACDPHSGHFV",
    "ADDVKLWRQRGMSTW",
    "ADKPDESTL",
    "AEENDEENVEEVEENVEENV",
    "AEHQAIIRDVLTASD"
]

# Define the set of unique characters (amino acids)
unique_characters = sorted(set(''.join(sequences)))

# Create a mapping from characters to indices
char_to_index = {char: i for i, char in enumerate(unique_characters)}

# Convert each sequence to its index representation
indexed_sequences = [[char_to_index[char] for char in seq] for seq in sequences]

# Convert indexed sequences to PyTorch tensors
tensor_sequences = [torch.tensor(seq) for seq in indexed_sequences]

# Pad sequences to a fixed length
padded_sequences = pad_sequence(tensor_sequences, batch_first=True, padding_value=-1)

# Print padded sequences
print(padded_sequences)


tensor([[ 0,  0, 14,  1,  7,  2,  5,  0,  4, 14, 12,  8,  0, 16,  2,  5, -1, -1,
         -1, -1],
        [ 0,  1,  2, 12,  6, 15,  5,  6,  4, 17, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1],
        [ 0,  2,  2, 17,  8,  9, 18, 14, 13, 14,  5, 10, 15, 16, 18, -1, -1, -1,
         -1, -1],
        [ 0,  2,  8, 12,  2,  3, 15, 16,  9, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1],
        [ 0,  3,  3, 11,  2,  3,  3, 11, 17,  3,  3, 17,  3,  3, 11, 17,  3,  3,
         11, 17],
        [ 0,  3,  6, 13,  0,  7,  7, 14,  2, 17,  9, 16,  0, 15,  2, -1, -1, -1,
         -1, -1]])


In [10]:
import torch
from torch.nn.utils.rnn import pad_sequence

# List of protein sequences
sequences = [
    "AARCIDGAFRPKATDG",
    "ACDPHSGHFV",
    "ADDVKLWRQRGMSTW",
    "ADKPDESTL",
    "AEENDEENVEEVEENVEENV",
    "AEHQAIIRDVLTASD"
]

# Define the set of unique characters (amino acids)
unique_characters = sorted(set(''.join(sequences)))

# Additional tokens
pad_token = '<PAD>'
start_token = '<START>'
end_token = '<END>'
unknown_token = '<UNK>'

# Create a mapping from characters to indices
char_to_index = {char: i + 4 for i, char in enumerate(unique_characters)}
char_to_index[pad_token] = 0
char_to_index[start_token] = 1
char_to_index[end_token] = 2
char_to_index[unknown_token] = 3

# Convert each sequence to its index representation
indexed_sequences = [[char_to_index.get(char, char_to_index[unknown_token]) for char in seq] for seq in sequences]

# Convert indexed sequences to PyTorch tensors
tensor_sequences = [torch.tensor(seq) for seq in indexed_sequences]

# Pad sequences to a fixed length
padded_sequences = pad_sequence(tensor_sequences, batch_first=True, padding_value=char_to_index[pad_token])

# Print padded sequences
print(padded_sequences)


tensor([[ 4,  4, 18,  5, 11,  6,  9,  4,  8, 18, 16, 12,  4, 20,  6,  9,  0,  0,
          0,  0],
        [ 4,  5,  6, 16, 10, 19,  9, 10,  8, 21,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [ 4,  6,  6, 21, 12, 13, 22, 18, 17, 18,  9, 14, 19, 20, 22,  0,  0,  0,
          0,  0],
        [ 4,  6, 12, 16,  6,  7, 19, 20, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [ 4,  7,  7, 15,  6,  7,  7, 15, 21,  7,  7, 21,  7,  7, 15, 21,  7,  7,
         15, 21],
        [ 4,  7, 10, 17,  4, 11, 11, 18,  6, 21, 13, 20,  4, 19,  6,  0,  0,  0,
          0,  0]])


In [11]:
import torch
from torch.nn.utils.rnn import pad_sequence

# List of protein sequences
sequences = [
    "AARCIDGAFRPKATDG",
    "ACDPHSGHFV",
    "ADDVKLWRQRGMSTW",
    "ADKPDESTL",
    "AEENDEENVEEVEENVEENV",
    "AEHQAIIRDVLTASD"
]

# Define the set of unique characters (amino acids) and special tokens
special_tokens = ['<PAD>', '<SOS>', '<EOS>']
unique_characters = sorted(set(''.join(sequences)) | set(special_tokens))

# Create a mapping from characters to indices
char_to_index = {char: i for i, char in enumerate(unique_characters)}

# Create a reverse mapping from indices to characters
index_to_char = {i: char for char, i in char_to_index.items()}

# Convert each sequence to its index representation
indexed_sequences = [[char_to_index[char] for char in seq] for seq in sequences]

# Convert indexed sequences to PyTorch tensors
tensor_sequences = [torch.tensor(seq) for seq in indexed_sequences]

# Pad sequences to a fixed length
padded_sequences = pad_sequence(tensor_sequences, batch_first=True, padding_value=char_to_index['<PAD>'])

# Print padded sequences
print("Padded sequences:")
print(padded_sequences)

# Function to convert indices to readable tokens
def indices_to_tokens(indices):
    return [index_to_char[index] for index in indices]

# Test conversion function
for i, seq in enumerate(padded_sequences):
    print(f"Sequence {i + 1}:")
    print("Indices:", seq.tolist())
    print


Padded sequences:
tensor([[ 3,  3, 17,  4, 10,  5,  8,  3,  7, 17, 15, 11,  3, 19,  5,  8,  1,  1,
          1,  1],
        [ 3,  4,  5, 15,  9, 18,  8,  9,  7, 20,  1,  1,  1,  1,  1,  1,  1,  1,
          1,  1],
        [ 3,  5,  5, 20, 11, 12, 21, 17, 16, 17,  8, 13, 18, 19, 21,  1,  1,  1,
          1,  1],
        [ 3,  5, 11, 15,  5,  6, 18, 19, 12,  1,  1,  1,  1,  1,  1,  1,  1,  1,
          1,  1],
        [ 3,  6,  6, 14,  5,  6,  6, 14, 20,  6,  6, 20,  6,  6, 14, 20,  6,  6,
         14, 20],
        [ 3,  6,  9, 16,  3, 10, 10, 17,  5, 20, 12, 19,  3, 18,  5,  1,  1,  1,
          1,  1]])
Sequence 1:
Indices: [3, 3, 17, 4, 10, 5, 8, 3, 7, 17, 15, 11, 3, 19, 5, 8, 1, 1, 1, 1]
Sequence 2:
Indices: [3, 4, 5, 15, 9, 18, 8, 9, 7, 20, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Sequence 3:
Indices: [3, 5, 5, 20, 11, 12, 21, 17, 16, 17, 8, 13, 18, 19, 21, 1, 1, 1, 1, 1]
Sequence 4:
Indices: [3, 5, 11, 15, 5, 6, 18, 19, 12, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Sequence 5:
Indices: [3, 6, 6, 14,

In [22]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=10, shuffle=True)


a = [100000-i for i in range(100)]

for ix, (tr, ts) in enumerate(kf.split(a)):
    print(tr)
    break

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 16 17 18 19 20 22 23 24 26
 27 28 29 30 31 32 33 34 36 37 38 39 40 41 42 44 45 46 48 49 50 52 53 54
 55 56 57 58 60 61 62 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80
 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98]
